In [1]:
import pandas as pd
from PIL import Image 
from glob import glob

DIR_WHERE_IMAGES_ARE = "data/trimmed/*/*"
files=glob(DIR_WHERE_IMAGES_ARE)

def file_size(fn):
    im=Image.open(fn)
    return im.size

# Using a map get all the file sizes
sizes=list(map(file_size,files))

#As thr two lists are same size and same order  - zip
file_size=list(zip(files,sizes))

# I need to extract the Size - which is a tuple as 2 fields
file_size = [[fs[0], fs[1][0], fs[1][1]] for fs in list(zip(files,sizes))]

In [2]:
df=pd.DataFrame.from_records(file_size,columns=['filename','X','Y'])

In [3]:
df['Class']=df.filename.apply(lambda x: x.split('/')[2])
df['Ratio']=df.X/df.Y
df['Horiz']=df.Ratio.apply(lambda x: True if x < 1.0 else False)

In [71]:
df.head()

,filename,X,Y,Ratio,Horiz,Class
0,data/trimmed/Cape_May_Warbler/Cape_May_Warbler...,146,170,0.858824,True,Cape_May_Warbler
1,data/trimmed/Cape_May_Warbler/Cape_May_Warbler...,206,325,0.633846,True,Cape_May_Warbler
2,data/trimmed/Cape_May_Warbler/Cape_May_Warbler...,329,254,1.295276,False,Cape_May_Warbler
3,data/trimmed/Cape_May_Warbler/Cape_May_Warbler...,241,235,1.025532,False,Cape_May_Warbler
4,data/trimmed/Cape_May_Warbler/Cape_May_Warbler...,376,149,2.523490,False,Cape_May_Warbler

In [88]:
df.groupby(['Class'])['Ratio'].mean().to_frame().sort_values(['Ratio'])

                                   Ratio
Class
Red_cockaded_Woodpecker         0.571732
Brown_Creeper                   0.596107
American_Three_toed_Woodpecker  0.634513
Western_Wood_Pewee              0.714584
Pileated_Woodpecker             0.723756
Crested_Auklet                  0.742845
Cedar_Waxwing                   0.758499
Downy_Woodpecker                0.760428
Olive_sided_Flycatcher          0.778771
Red_bellied_Woodpecker          0.791057
Least_Flycatcher                0.793457
Red_faced_Cormorant             0.797249
Parakeet_Auklet                 0.817746
Least_Auklet                    0.824797
Yellow_bellied_Flycatcher       0.831736
Red_headed_Woodpecker           0.835580
Nelson_Sharp_tailed_Sparrow     0.882020
Green_Violetear                 0.887970
Seaside_Sparrow                 0.900870
Tropical_Kingbird               0.906436
Groove_billed_Ani               0.908118
Mangrove_Cuckoo                 0.918079
White_breasted_Kingfisher       0.918671
Great_Crested_Flycatcher        0.921976
Baird_Sparrow                   0.924823
Bank_Swallow                    0.928943
Acadian_Flycatcher              0.950644
Black_billed_Cuckoo             0.958177
Brown_Pelican                   0.967921
Bobolink                        0.968354
...                                  ...
Green_Kingfisher                1.391648
Cape_May_Warbler                1.392043
Tennessee_Warbler               1.397396
Cerulean_Warbler                1.405251
White_breasted_Nuthatch         1.416676
Northern_Waterthrush            1.416879
Mallard                         1.422982
Northern_Fulmar                 1.429764
Scissor_tailed_Flycatcher       1.434466
Common_Tern                     1.466975
Bay_breasted_Warbler            1.467786
Chuck_will_Widow                1.494559
Worm_eating_Warbler             1.501125
Forsters_Tern                   1.521048
Rhinoceros_Auklet               1.521647
Long_tailed_Jaeger              1.522071
Elegant_Tern                    1.523917
Whip_poor_Will                  1.531839
Nighthawk                       1.552496
White_Pelican                   1.569587
Artic_Tern                      1.570758
Pied_billed_Grebe               1.578711
Eared_Grebe                     1.650708
Horned_Grebe                    1.663203
Least_Tern                      1.685856
Western_Grebe                   1.799456
Hooded_Merganser                1.903575
Gadwall                         1.978689
Red_breasted_Merganser          2.002512
Pacific_Loon                    2.116648

[200 rows x 1 columns]

In [ ]:
df.sort